requires 'DBI';
requires 'DBD::SQLite';
requires 'DBD::Pg';
requires 'Data::Dumper';
requires 'Getopt::Long';
requires 'Moo';
requires 'Mojo::IOLoop';
requires 'Mojolicious';
requires 'Algorithm::Combinatorics';
requires 'Digest::SHA';
requires 'JSON';
requires 'MIME::Base64';

on 'test' => sub {
    requires 'Test::More', '>= 1.302';
    requires 'Test::Exception';
    requires 'Test::MockModule';
    requires 'Test::Output';
    requires 'File::Temp';
};
